name: ProteinCore
version: 1.0
main: com.protein.proteincore.ProteinCore
depend: [Factions, Vault, WorldGuard]
authors: [LilProteinShake]
commands:
  genbucket:
    description: Command to manage GenBuckets.
  trenchtool:
    description: Command to manage TrenchTools.
  freeze:
    description: Command to freeze people.